[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["cd backend && python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && python -c \"import sys; sys.path.append('.'); from main import app; import uvicorn; uvicorn.run(app, host='0.0.0.0', port=int('$PORT'))\""
